/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/sjgBaVBAqvd
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

"use client";

import Link from "next/link";
import React, { useEffect } from "react";
import Image from "next/image";
import { Avatar, AvatarImage, AvatarFallback } from "~/components/ui/avatar";
import SkillCategorySection from "../SkillCategorySection";
//import profileImage from "hc_pfp.png";
import {
  ArchiveIcon,
  Brain,
  Layers2Icon,
  PenToolIcon,
  PuzzleIcon,
  TerminalIcon,
} from "lucide-react";

const categories = [
  {
    icon: TerminalIcon,
    title: "Programming Languages",
    items: [
      "Python",
      "JavaScript",
      "TypeScript",
      "C#",
      "Java",
      "Lua",
      "C",
      "Kotlin",
    ],
  },
  {
    icon: Layers2Icon,
    title: "Frameworks",
    items: ["PyTorch", "HuggingFace", "Keras", "TensorFlow"],
  },
  {
    icon: DatabaseIcon,
    title: "Databases",
    items: ["MySQL", "Prisma", "BigQuery", "VectorDB"],
  },
  {
    icon: ArchiveIcon,
    title: "Libraries",
    items: [
      "NumPy",
      "Pandas",
      "HuggingFace Transformers",
      "Scikit-Learn",
      "OpenCV",
      "Matplotlib",
      "Seaborn",
      "Tesseract",
      "LangChain",
      "Apache Spark",
    ],
  },
  {
    icon: Brain,
    title: "Models",
    items: [
      "LLM",
      "CNN",
      "Transformers",
      "Diffusers",
      "OCR",
      "Random Forest",
      "Autoencoders",
      "YOLO",
      "SVM",
      "KNN",
      "K-Means",
      "Regression",
      "GPT",
      "Claude",
      "Gemini",
      "StableDiffusion",
    ],
  },
  {
    icon: CloudIcon,
    title: "Infrastructure",
    items: [
      "GCP",
      "Docker",
      "AWS",
      "Kubernetes (K8S)",
      "Vercel",
      "Jenkins",
      "GitHub Actions",
      "FastAPI",
      "Airflow",
    ],
  },
];

export function Home() {
  useEffect(() => {
    const handleScroll = (e) => {
      e.preventDefault();
      const href = e.currentTarget.getAttribute("href");
      const targetId = href.replace(/.*\#/, "");
      const elem = document.getElementById(targetId);
      elem?.scrollIntoView({
        behavior: "smooth",
      });
    };

    const links = document.querySelectorAll('a[href^="#"]');
    links.forEach((link) => {
      link.addEventListener("click", handleScroll);
    });

    return () => {
      links.forEach((link) => {
        link.removeEventListener("click", handleScroll);
      });
    };
  }, []);

  const navItems = [
    { icon: <UserIcon size={20} />, label: "About Me", href: "#about-me" },
    {
      icon: <BriefcaseIcon size={20} />,
      label: "Career Journey",
      href: "#career-journey",
    },
    {
      icon: <CodeIcon size={20} />,
      label: "Tech Arsenal",
      href: "#tech-arsenal",
    },
    {
      icon: <StarIcon size={20} />,
      label: "Endorsements",
      href: "#endorsements",
    },
    { icon: <MailIcon size={20} />, label: "Contact", href: "#contact" },
  ];

  return (
    <div className="flex min-h-screen flex-col bg-background text-foreground">
      <header className="group fixed left-0 top-0 z-10 flex h-screen w-16 flex-col items-center justify-center overflow-hidden bg-primary text-primary-foreground transition-all duration-500 hover:w-48">
        <div className="flex w-full flex-col items-center justify-center">
          <div className="mb-8 text-2xl font-bold">HC</div>
          <nav className="flex w-full flex-col items-center">
            {navItems.map((item, index) => (
              <Link
                key={index}
                href={item.href}
                className="flex w-full items-center justify-center py-3 transition-all duration-500 hover:bg-primary-foreground/10"
                prefetch={false}
              >
                <div className="relative flex h-8 w-full items-center justify-center group-hover:justify-start group-hover:pl-[18px]">
                  <div className="absolute left-1/2 flex -translate-x-1/2 transform items-center justify-center transition-all duration-500 group-hover:left-[36px] group-hover:translate-x-0">
                    {item.icon}
                  </div>
                  <span className="pointer-events-none absolute left-12 whitespace-nowrap text-sm opacity-0 transition-all duration-300 group-hover:left-[83px] group-hover:opacity-100">
                    {item.label}
                  </span>
                </div>
              </Link>
            ))}
          </nav>
        </div>
      </header>
      <main className="flex-1 pb-24 pt-16 md:pl-16">
        <section id="about-me" className="px-4 py-12 md:px-8 lg:px-12">
          <div className="mx-auto flex max-w-3xl items-start gap-8">
            <Image
              src="/hc_pfp.png"
              alt="Profile Picture"
              width={180}
              height={180}
              className="rounded-full object-cover"
            />
            <div>
              <h1 className="text-4xl font-bold">Haim Cohen</h1>
              <p className="mt-4 text-lg text-muted-foreground">
                Hi, I’m Haim—a Data Scientist and Machine Learning Engineer with
                over five years of experience in developing AI tools that make a
                tangible impact.
                <br />
                <br />
                I’ve had the chance to work across gaming, business
                communication, and fintech, where I’ve focused on applying my
                expertise in machine learning and data analysis to create
                systems that are both practical and reliable. I love diving into
                complex challenges, no matter the field. Whether it's exploring
                new technologies or optimizing existing systems, I’m all about
                hands-on work, collaboration, and continuous learning.
                <br />
                <br />
                My goal is simple: to build solutions that work and make a real
                difference. If there’s a challenge ahead, I’m ready to tackle it
                head-on.
              </p>
            </div>
          </div>
        </section>
        <section id="career-journey" className="px-4 py-12 md:px-8 lg:px-12">
          <div className="mx-auto max-w-3xl">
            <h2 className="text-3xl font-bold">Career Journey</h2>
            <div className="mt-8 space-y-8">
              <div className="grid grid-cols-[auto_1fr] items-start gap-4">
                <div className="rounded-full bg-primary px-4 py-2 text-primary-foreground">
                  2019-2021
                </div>
                <div>
                  <h3 className="text-xl font-semibold">
                    Computer Vision Engineer{" "}
                    <span className="text-base font-light text-gray-500">
                      at ShapeShift Gaming
                    </span>
                  </h3>
                  <p className="mt-2 text-muted-foreground">
                    At ShapeShift Gaming, our mission was to revolutionize the
                    live-streaming experience by extracting game elements and UI
                    from real-time creator content to build a recommendation
                    system tailored for platforms like Twitch.
                    <br />
                    <br />
                    My contributions included implementing OCR with classical CV
                    techniques—such as bitwise operations, contours, and
                    template matching—alongside neural networks (NNs), KNN, and
                    Tesseract, to accurately extract and analyze in-game UI
                    elements. To further enhance the robustness of our models,
                    we created augmented data by simulating game elements in
                    challenging environments (e.g., low bitrate, blurry
                    backgrounds, game effects) and automatically tagged this
                    data, significantly improving our system's accuracy in
                    real-world conditions.
                    <br />
                    <br />
                    We further enriched our data pipeline by integrating various
                    methods from CV, DSP, and NLP to gather essential
                    information from streamers. For example, in our gender
                    recognition efforts, we used a combination of CV (VGG-Face
                    DCNN), DSP (pyAudioAnalysis), and NLP (TF-IDF) to predict
                    and enhance gender accuracy, contributing to more
                    personalized recommendations.
                    <br />
                    <br />
                    In a specific project involving Fortnite, we needed to
                    determine the number of players on screen to identify the
                    current game mode. To achieve this, we employed a YOLO human
                    detection model, which I finetuned through transfer learning
                    on game character data. This model, along with other
                    optimizations, significantly improved our system’s ability
                    to accurately detect and classify game modes. These efforts
                    led to a substantial improvement in recommendation accuracy,
                    content discovery, and overall viewer engagement.
                  </p>
                </div>
              </div>
              <div className="grid grid-cols-[auto_1fr] items-start gap-4">
                <div className="rounded-full bg-primary px-4 py-2 text-primary-foreground">
                  2021-2023
                </div>
                <div>
                  <h3 className="text-xl font-semibold">
                    Deep Learning Researcher{" "}
                    <span className="text-base font-light text-gray-500">
                      at Substrata
                    </span>
                  </h3>
                  <p className="mt-2 text-muted-foreground">
                    At Substrata, we focused on enhancing business communication
                    by analyzing real-time human dynamics to uncover attitudes,
                    intentions, and power dynamics, helping deal-makers sell
                    smarter and close more deals. My primary contribution was
                    the development of a non-verbal LLM that interprets and
                    predicts power dynamics in business interactions.
                    <br />
                    <br />
                    By analyzing both manually tagged data and real-time
                    interactions, we achieved a 20% improvement in communication
                    effectiveness, directly impacting deal outcomes. In addition
                    to my technical contributions, I played a key role in
                    fostering a culture of meticulous documentation and thorough
                    research. This focus on detailed documentation ensured that
                    our models were not only effective but also well-understood
                    and maintainable, laying the groundwork for long-term
                    success and scalability.
                    <br />
                    <br />
                    I also developed a regression model to optimize email
                    sending times by analyzing historical interaction data,
                    which resulted in a 15% increase in deal-closing rates.
                    Additionally, I significantly improved the accuracy of our
                    email analysis system by creating a model for email
                    signature detection using high-quality, manually tagged
                    data, boosting the power dynamics score baseline by 40%.
                    <br />
                    <br />
                    Moreover, I took the initiative to showcase both new and
                    established technologies to my coworkers and stakeholders.
                    This not only allowed me to deepen my understanding of
                    various subjects but also contributed to a culture of
                    continuous learning and innovation within the team.
                    <br />
                    <br />
                    Throughout my time at Substrata, I was instrumental in
                    integrating AI-driven insights into our platform, enabling
                    users to navigate complex negotiations with greater
                    confidence and precision.
                  </p>
                </div>
              </div>
              <div className="grid grid-cols-[auto_1fr] items-start gap-4">
                <div className="rounded-full bg-primary px-4 py-2 text-primary-foreground">
                  2023-2024
                </div>
                <div>
                  <h3 className="text-xl font-semibold">
                    Lead Data Scientist{" "}
                    <span className="text-base font-light text-gray-500">
                      at ThetaMind
                    </span>
                  </h3>
                  <p className="mt-2 text-muted-foreground">
                    At ThetaMind, I co-founded and developed a fintech platform
                    focused on optimizing and scaling a proprietary options
                    trading algorithm. This experience not only deepened my
                    technical expertise but also provided valuable insights into
                    the intricacies of the fintech industry, including
                    regulatory considerations and market dynamics.
                    <br />
                    <br />
                    increased algorithm performance by 25% through detailed
                    research and identification of key optimization areas using
                    classic statistical analysis and machine learning techniques
                    like regression and random forests, measured using
                    historical market data to enhance early development phases.
                    <br />
                    <br />
                    As a co-founder, I took on responsibilities beyond the
                    technical realm, from strategic planning to investor
                    relations, gaining a holistic understanding of what it takes
                    to build and scale a startup. I also architected an
                    efficient backend service solution to handle real-time
                    symbol and options data, capable of withstanding 13k
                    requests per minute. This was achieved by leveraging NestJS
                    to build a scalable microservices architecture and deploying
                    on Vercel for optimized serverless performance. The system's
                    reliability was validated through rigorous stress tests
                    under simulated market conditions, ensuring it could perform
                    reliably during live trading sessions.
                    <br />
                    <br />
                    This experience solidified my passion for combining
                    technical innovation with strategic business insight. It has
                    equipped me with a unique blend of skills that I am eager to
                    apply to new challenges, whether in fintech or beyond. The
                    journey at ThetaMind has been a testament to the power of
                    interdisciplinary collaboration and the impact of
                    well-engineered solutions on real-world problems.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="tech-arsenal" className="px-4 py-8 md:px-8 lg:px-12">
          <div className="mx-auto max-w-6xl">
            <div className="mx-auto max-w-3xl">
              <h2 className="text-3xl font-bold">Tech Arsenal</h2>
            </div>
            <section className="px-4 py-8 md:px-8 lg:px-12">
              <div className="mx-auto max-w-3xl">
                <div className="grid grid-cols-1 items-start justify-start gap-6 md:grid-cols-6">
                  {categories.map((category, index) => (
                    <SkillCategorySection
                      key={index}
                      icon={category.icon}
                      title={category.title}
                      items={category.items}
                    />
                  ))}
                </div>
              </div>
            </section>
          </div>
        </section>

        <section id="endorsements" className="px-4 py-12 md:px-8 lg:px-12">
          <div className="mx-auto max-w-3xl">
            <h2 className="text-3xl font-bold">Endorsements</h2>
            <div className="mt-8 space-y-8">
              <div className="rounded-lg bg-muted p-6">
                <p className="text-lg italic">
                  Haim is one of those rare talents who brings both deep
                  technical expertise and a genuine passion for innovation to
                  the table. From day one at Substrata, he was more than just a
                  brilliant engineer—he was a driving force that energized our
                  team. His ability to turn complex ideas into practical,
                  impactful solutions is something that still impresses me.
                  Beyond his technical skills, Haim has a knack for fostering a
                  culture of curiosity and continuous learning. He doesn’t just
                  solve problems; he inspires those around him to reach higher
                  and think bigger. Working with Haim was not just productive—it
                  was genuinely fun, and I’m excited to see where his journey
                  takes him next. Wherever Haim goes, he’s sure to make a big
                  impact, and I’m eager to see what he’ll accomplish in the
                  future.
                </p>
                <div className="mt-4 flex items-center gap-4">
                  <Avatar>
                    <AvatarImage src="/baruchi.jpeg" />
                    <AvatarFallback>BH</AvatarFallback>
                  </Avatar>
                  <div>
                    <h4 className="text-lg font-semibold">Baruchi Har-Lev</h4>
                    <p className="text-muted-foreground">
                      Co-Founder & CTO, SubStrata
                    </p>
                  </div>
                </div>
              </div>
              <div className="rounded-lg bg-muted p-6">
                <p className="text-lg italic">
                  It’s hard to do Haim justice with such few characters, but the
                  first words that come to mind are selfless, dedicated, and
                  extremely trustworthy. I hired Haim as an entry-level python
                  engineer and grew to be one of the most phenomenal engineers
                  on our team. His drive and hustle, paired with his infectious
                  passion for gaming and code, made for a winning combo, and he
                  shows no signs of slowing down. It’s been a true honor to work
                  side by side with him, I highly recommend him!
                </p>
                <div className="mt-4 flex items-center gap-4">
                  <Avatar>
                    <AvatarImage src="/kevin.png" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div>
                    <h4 className="text-lg font-semibold">Kevin Edry</h4>
                    <p className="text-muted-foreground">
                      Co-Founder & CTO, Shapeshift Gaming
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="contact" className="px-4 py-12 md:px-8 lg:px-12">
          <div className="mx-auto max-w-3xl">
            <h2 className="text-3xl font-bold">Contact</h2>
            <div className="mt-8 space-y-4">
              <div className="flex items-center gap-4">
                <MailIcon className="h-6 w-6 text-muted-foreground" />
                <a
                  href="mailto:haim.nova@gmail.com"
                  className="text-muted-foreground hover:underline"
                  onClick={(e) => {
                    e.stopPropagation();
                    window.location.href = e.currentTarget.href;
                  }}
                >
                  haim.nova@gmail.com
                </a>
              </div>
              <div className="flex items-center gap-4">
                <LinkedinIcon className="h-6 w-6 text-muted-foreground" />
                <a
                  href="https://www.linkedin.com/in/cohen-haim"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-muted-foreground hover:underline"
                  onClick={(e) => {
                    e.stopPropagation();
                    window.open(e.currentTarget.href, "_blank");
                  }}
                >
                  linkedin.com/in/cohen-haim
                </a>
              </div>
              <div className="flex items-center gap-4">
                <GithubIcon className="h-6 w-6 text-muted-foreground" />
                <a
                  href="https://github.com/CohenHaim"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-muted-foreground hover:underline"
                  onClick={(e) => {
                    e.stopPropagation();
                    window.open(e.currentTarget.href, "_blank");
                  }}
                >
                  github.com/CohenHaim
                </a>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

function BriefcaseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
      <rect width="20" height="14" x="2" y="6" rx="2" />
    </svg>
  );
}

function CloudIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z" />
    </svg>
  );
}

function CodeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  );
}

function DatabaseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <ellipse cx="12" cy="5" rx="9" ry="3" />
      <path d="M3 5V19A9 3 0 0 0 21 19V5" />
      <path d="M3 12A9 3 0 0 0 21 12" />
    </svg>
  );
}

function GithubIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  );
}

function HeartHandshakeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
      <path d="M12 5 9.04 7.96a2.17 2.17 0 0 0 0 3.08v0c.82.82 2.13.85 3 .07l2.07-1.9a2.82 2.82 0 0 1 3.79 0l2.96 2.66" />
      <path d="m18 15-2-2" />
      <path d="m15 18-2-2" />
    </svg>
  );
}

function LampIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2h8l4 10H4L8 2Z" />
      <path d="M12 12v6" />
      <path d="M8 22v-2c0-1.1.9-2 2-2h4a2 2 0 0 1 2 2v2H8Z" />
    </svg>
  );
}

function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  );
}

function MailIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  );
}

function NutIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 4V2" />
      <path d="M5 10v4a7.004 7.004 0 0 0 5.277 6.787c.412.104.802.292 1.102.592L12 22l.621-.621c.3-.3.69-.488 1.102-.592A7.003 7.003 0 0 0 19 14v-4" />
      <path d="M12 4C8 4 4.5 6 4 8c-.243.97-.919 1.952-2 3 1.31-.082 1.972-.29 3-1 .54.92.982 1.356 2 2 1.452-.647 1.954-1.098 2.5-2 .595.995 1.151 1.427 2.5 2 1.31-.621 1.862-1.058 2.5-2 .629.977 1.162 1.423 2.5 2 1.209-.548 1.68-.967 2-2 1.032.916 1.683 1.157 3 1-1.297-1.036-1.758-2.03-2-3-.5-2-4-4-8-4Z" />
    </svg>
  );
}

function PiIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="9" x2="9" y1="4" y2="20" />
      <path d="M4 7c0-1.7 1.3-3 3-3h13" />
      <path d="M18 20c-1.7 0-3-1.3-3-3V4" />
    </svg>
  );
}

function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  );
}

function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  );
}
